betrusted-soc: prefix key2bits.py call with sys.executable
On Unix systems, the shebang allows python scripts to be run as if they
were binaries.  However, not all systems support this.

For example, running `betrusted-soc.py` on Windows produces the
following error:

	Traceback (most recent call last):
	  File ".\betrusted-soc.py", line 1442, in <module>
	    ret = main()
	  File ".\betrusted-soc.py", line 1415, in main
	    subprocess.call(['./key2bits.py', '-c', '-k../../keystore.bin', '-r../../rom.db'], cwd='deps/rom-locate', stdout=libfile)
	  File "D:\Software\Python37\lib\subprocess.py", line 339, in call
	    with Popen(*popenargs, **kwargs) as p:
	  File "D:\Software\Python37\lib\subprocess.py", line 800, in __init__
	    restore_signals, start_new_session)
	  File "D:\Software\Python37\lib\subprocess.py", line 1207, in _execute_child
	    startupinfo)
	OSError: [WinError 193] %1 is not a valid Win32 application

This can be solved by specifying the interpreter path, which is available
in `sys.executable`.

Signed-off-by: Sean Cross <sean@xobs.io>